version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
    depends_on:
      - backend

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      PORT: 8080
      PG_CONNECTION_STRING: postgresql://postgres:example@db/postgres
    tty: true

  frontend:
    build: ./frontend
    tty: true

volumes:
  db:
