version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server --save 60 1
    volumes:
      - redis:/data

  proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
      - redis
    environment:
      PORT: 8080
      PG_CONNECTION_STRING: postgresql://postgres:example@db/postgres
      SESSION_SECRET: 3jraFAUf
    tty: true

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    tty: true

volumes:
  db:
  redis:
