version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      PORT: 5000
      PG_CONNECTION_STRING: postgresql://postgres:example@db/postgres
    volumes:
      - "./src:/usr/src/app/src"
    tty: true

volumes:
  db:
