version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PORT: 8080
      PG_CONNECTION_STRING: postgresql://postgres:example@db/postgres
    tty: true
    volumes:
      - "./backend/src:/usr/src/app/src"

volumes:
  db:
