version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.development
    depends_on:
      - db
    environment:
      PORT: 8080
      PG_CONNECTION_STRING: postgresql://postgres:example@db/postgres
    tty: true
    volumes:
      - "./backend/src:/usr/src/app/backend/src"
      - "./shared:/usr/src/app/shared"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.development
    tty: true
    volumes:
      - "./frontend/src:/usr/src/app/frontend/src"
      - "./shared:/usr/src/app/shared"

volumes:
  db:
